# Nixpacks configuration for Railway
# Force Python detection and ignore Node.js files

[start]
cmd = "py3 app_ultimate_mem0.py"

[phases.build]
cmds = ["pip install -r requirements.txt"]

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"
NIXPACKS_BUILD_SYSTEM = "pip"

[[providers]]
name = "python"
