# Nixpacks configuration for Railway
# Match the successful build pattern exactly

[start]
cmd = "python app_ultimate_mem0.py"

[phases.build]
cmds = ["pip install -r requirements.txt"]

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

