[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "python bonzai_app.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { }

# Service configuration
[service]
name = "bonzai-backend"

# Build configuration
[build.buildCommand]
command = "pip install --no-cache-dir -r requirements.txt"

# Health check
[healthCheck]
path = "/api/health"
httpHeaders = { }
initialDelaySeconds = 30
periodSeconds = 10
timeoutSeconds = 5
successThreshold = 1
failureThreshold = 3
